blank_issues_enabled: false
contact_links:
  - name: Questions & discussion
    url: https://github.com/HAPNlab/mid-task-deterministic/discussions
    about: For general questions and usage help, please start a discussion instead of opening an issue.
